server:
  port: ${PORT:8084}

spring:
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:h2:mem:cinema
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console